info/apps/actividades/urls.py
from django.urls import path,include

from django.conf.urls.static import static
from django.conf import settings

from . import views

app_name = 'actividades'

urlpatterns = [
    path('listar/', views.Acts, name = 'listar_actividades'),
    
    path('detalle/<int:pk>', views.Detalle_Actividad, name = 'detalle_actividad'),
]

info/apps/noticias/urls.py
from django.urls import path
from . import views

app_name='noticias'

urlpatterns = [
    path('listar/', views.Listar, name='listar_noticias'),
    path('listarPorFecha/', views.ListarporFecha, name='listar_noticiasporFecha'),
    path('MostrarNoticia/<int:pk>/', views.DetalleNoticia.as_view(), name='MostrarNoticia'),
    path('listarPatronales/', views.ListarPatronales, name='listar_noticiasPatronales'),
    path('listarSociales/', views.ListarSociales, name='listar_noticiasSociales'),
    path('add_comentario/<int:pk>', views.Agregar_Comentario, name="agregar_comentario"),
    path('delete_comentario/<int:pk>', views.Eliminar_Comentario, name="eliminar_comentario"),
]

info/apps/usuarios/urls.py
from django.urls import path
from . import views

from django.contrib.auth import views as auth

app_name= 'usuarios'

urlpatterns = [
    
    path('registrarse/',views.Registrarse.as_view(), name='Registrarse'),
    
    path('login/',auth.LoginView.as_view(template_name='usuarios/Logearse.html'),name='Logearse'),
    path('logout/',auth.LogoutView.as_view(),name="logout"),
    
]

info/info/urls.py
from django.contrib import admin
from django.urls import path,include

from django.conf.urls.static import static
from django.conf import settings

from . import views



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.Home, name = 'home'),
    path('contacto/', views.contacto, name = 'contacto'),
    path('mision_vision/', views.mision_vision, name = 'mision_vision'),
    path('eventos/', views.eventos, name = 'eventos'),
    path('noticias/',include('apps.noticias.urls')),
    path('usuarios/',include('apps.usuarios.urls')),
    path('Actividades/',include('apps.actividades.urls')),
    
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

info/templates/base.html
{%load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>CEBs Castelli</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.2/css/all.min.css" integrity="sha512-1sCRPdkRXhBV2PBLUdRb4tMg1w2YPf37qatUFeS7zlBy7jJI8Lf4VHwWfZZfpXtYSLy85pkm9GaYVYMfw5BC1A==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <!-- CSS Local -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}"> <!-- No funciona? -->
    <link rel="stylesheet" type="text/css" href="../static/css/base.css">
    <link rel="icon" href="{% static 'img/iconcebs.ico' %}">
</head>
<body>
  <!-- Cabecera -->
  <header>
    <nav class="navbar navbar-expand-md fixed-top  p-md-2">
        <div class="container-fluid">
        <a style="margin-left: 20px;" class="navbar-brand" href="{%url 'home'%}">
          <img  style="width: 40px; " src="{% static 'img/iconcebs_1.svg' %} " alt="logoCBEs">
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse justify-content-end" id="navbarNavDropdown">
            <ul class="navbar-nav" >
            <li class="nav-item">
              <a class="nav-link" aria-current="page" href="{%url 'home'%}">Inicio</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{%url 'noticias:listar_noticias' %}">Noticias</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{%url 'eventos' %}">Eventos</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{%url 'actividades:listar_actividades' %}">Actividades</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{%url 'mision_vision' %}">Mision/Vision</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{%url 'contacto' %}">Contacto</a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false" style="margin-right:55px;">Cuenta </a>
                <ul class="dropdown-menu">
                    {% if user.is_authenticated %}
                            <li><a class="dropdown-item">HOLA {{user.username}}!!</a></li>
                            <li><a class="dropdown-item" href="{% url 'usuarios:logout' %}">Salir</a></li>
                        {% else %}
                            <li><a class="dropdown-item" href="{%url 'usuarios:Logearse'%}">Ingresar</a></li>
                            <li><a class="dropdown-item" href="{%url 'usuarios:Registrarse'%}">Registrarse</a></li>
                        {% endif %}
                </ul>
            </li>
            </ul>
        </div>
        </div>
    </nav>
  </header>
  
  <div style="margin-bottom: 2rem;">
    {%block contenido%}

    {%endblock contenido%}
  </div>

    <!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
    <!-- JavaScript Font Awesome -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.2/js/all.min.js" integrity="sha512-8pHNiqTlsrRjVD4A/3va++W1sMbUHwWxxRPWNyVlql3T+Hgfd81Qc6FC5WMXDC+tSauxxzp1tgiAvSKFu1qIlA==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>



<!-- Footer -->
<footer class="text-center text-lg-start bg-light text-muted">
  <!-- Section: Social media -->
  <section class="d-flex justify-content-center justify-content-lg-between p-4 border-bottom" style="background-color: rgba(0, 0, 0, 0.10);">
    <!-- Left -->
 <!--   <div class="me-5 d-none d-lg-block">
      <span>Get connected with us on social networks:</span>
    </div>-->
    <!-- Left -->

    <!-- Right -->
    <!-- Right -->
  </section>
  <!-- Section: Social media -->

  <!-- Section: Links  -->
  <section>
    <div class="container text-center text-md-start mt-5">
      <!-- Grid row -->
      <div class="row mt-3">
        <!-- Grid column -->
        <div class="col-md-3 col-lg-4 col-xl-3 mx-auto mb-4">
          <!-- Content -->
          <h6 class="text-uppercase fw-bold mb-4">
            <i class="fa-solid fa-location-pin" style="margin-right: 8px;"></i>CEBs Castelli
          </h6>
          <p>
          Casa Angelelli Barrio “Chacra 108” Calle Mistol
          </p>
          <!-- <div class="span8">-->
            <iframe width="100%" height="65%
            " frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d28700.128473334105!2d-60.6314129!3d-25.9511104!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x94404ce2d270892f%3A0x1293d76246f10437!2sJuan%20Jos%C3%A9%20Castelli%2C%20Chaco!5e0!3m2!1ses-419!2sar!4v1660929705235!5m2!1ses-419!2sar"></iframe>
      <!--  </div>-->
        </div>

        <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4">
          <!-- Links -->
          <h6 class="text-uppercase fw-bold mb-3" style="margin-left:15px ;">Contacto</h6>
            <p><i class="fa-solid fa-circle me-3"></i>Delegada Diosesana:</p>
            <p><i class="fa-solid fa-user me-3"></i>Rosana Toledo</p><br>
            <p><i class="fa-solid fa-circle me-3"></i>Asesora de comunidades: </p>
            <p><i class="fa-solid fa-user me-3"></i>Ana Belen Molina </p>
            <p><i class="fa-solid fa-at me-2"></i>castellicebs19@gmail.com</p><br>
           <p><i class="fa-solid fa-location-pin me-3"></i>Juan José Castelli</p>
       <!--   <p><i class="fas fa-phone me-3"></i> 3644-349940</p>
          <p><i class="fas fa-print me-3"></i> 3644-621885</p>-->
        </div>
        <!-- Grid column -->
      </div>
      <!-- Grid row -->
    </div>
  </section>
  <!-- Section: Links  -->

  <!-- Copyright -->
  <div class="text-center p-4" style="background-color: rgba(0, 0, 0, 0.15);">
   
    <a class="text-reset fw-bold" href="https://capacitaciones.chaco.gob.ar">Informatorio 2022</a>
  </div>
  <!-- Copyright -->
</footer>



</body>
</html>

info/templates/contacto.html
{%extends 'base.html'%}
{%load static %}



{%block contenido %}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
<link rel="stylesheet" type="text/css" href="{% static 'css/contacto.css' %}">
<body>
    <div class="title-cards" style= "margin-top: 100px;">
        <h1>Contactanos</h1>
    </div>
    
    <div class="container-card">
        <div class="card">
            <figure>
                <img src="../static/img/correo.jpg">
            </figure>
            <div class="contenido-card">
                <h3>Correo Electrónico</h3>
                <p><i class="bi bi-envelope"></i> castellicebs19@gmail.com <br>Rosana Toledo - Delegada Diosesana<br>Ana Belen Molina - Asesora de comunidades</p>
            </div>
        </div>
        
        <div class="card">
            <div class="contenido-card">
                <iframe src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d3587.9280180446476!2d-60.6400559!3d-25.9375882!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x94404d66bddfecb9%3A0x1164c703b4c996ad!2sSal%C3%B3n%20Angelelli%2C%20comunidades%20Eclesiales%20de%20Base!5e0!3m2!1ses!2sar!4v1661639074053!5m2!1ses!2sar" width="100%" height="210" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
                <h3>Ubicación</h3>
                <p> <i class="bi bi-geo-alt-fill"></i> Casa Angelelli Barrio “Chacra 108” calle Mistol - J.J. Castelli</p>
            </div>
        </div>
        
        <div class="card">
            <figure>
                <img src="../static/img/redes.jpg">
            </figure>
            <div class="contenido-card">
                <h3>Redes Sociales</h3>
                <p>Unite a nuestro grupo de Facebook</p>
                <a href="https://www.facebook.com/groups/498186250237283/" target="_blank" class="face">
                    <i class="bi bi-facebook"></i>
                </a>
            </div>
        </div>  
    </div>
    
    <div class="container-form">
        <form action="">
            <div class="form">
                <h3>Formulario</h3>
                <p>Para más información por favor, pongase en contacto a traves de este simple formulario.</p>
                <div class="grupo">
                    <input type="text" name="" id=""  required><span class="barra"></span>
                    <label>Nombre</label>
                </div>
                <div class="grupo">
                    <textarea name="" id=""  required></textarea><span class="barra"></span>
                    <label>Mensaje</label>
                </div>
                <button type="submit">Enviar Mensaje</button>
            </div>
        </form>
    </div>     
</body>
{%endblock contenido%}

info/templates/eventos.html
{%extends 'base.html'%}
{%load static %}

{%block contenido%}
<link rel="stylesheet" href="{% static 'css/eventos.css' %}">


<div class = "my-body" style="text-align:center; margin-top: 100px;">
		<div id="container">
			<ul class="slider">
						
				<li id="slide1">
					<img src="{% static 'img/eventos.png' %}">
				</li>

				<li id="slide2">
					<img src="{% static 'img/proximamentee.png' %}">
				</li>
						
				<li id="slide3">
					<img src="{% static 'img/granjuntadacriollaa.png' %}">
				</li>
			</ul>

				<ul class="menu">
			    	<li>
			      		<a href="#slide1">1</a>
			    	</li>
			    	<li>
			      		<a href="#slide2">2</a>
			    	</li>
			     	<li>
			      		<a href="#slide3">3</a>
			    	</li>
			  	</ul>
		</div>
		
		<div id="container2">
			<div class="container2 py-10 px-10">
				<h1>Eventos de nuestra comunidad</h1><br>
		      		
		      	<h5>Dentro de nuestro apartado de eventos deseamos mostrarte los mismos a realizar y realizados dentro de las Comunidades Ecleciales de Base</h5><br>
		      			
				<h4> <i class="fa-solid fa-calendar-days"></i> CALENDARIO </h6><br>

				<h6> Nuestros eventos realizados los encontraras en los siguientes links en nuestro grupo de Facebook:</h6><br>
		      		
		      	<h6> DOMINGO, 24 DE FEBRERO DE 2019 </h6>
		      			
		      	<a href="https://www.facebook.com/events/2148033758587395/?acontext=%7B"event_action_history"%3A[%7B"surface"%3A"group"%7D]%7D">*6° Hormigazo - ¡Bajen Las Armas, Aquí Sólo Hay Pibes Comiendo!</a>
		      		
		      	<h6> DOMINGO, 25 DE FEBRERO DE 2018 </h6>	
		      		
		      	<a href="https://www.facebook.com/events/170949313543353/?acontext=%7B"event_action_history"%3A[%7B"surface"%3A"group"%7D]%7D">Subite, animate y pedaleá, vamos a dar una vuelta en la bicicleta de Pocho</a>

		      	<h6> DOMINGO, 26 DE FEBRERO DE 2017 </h6>
		      		
		      	<a href="https://www.facebook.com/events/221740204965203/?acontext=%7B"event_action_history"%3A[%7B"surface"%3A"group"%7D]%7D">“Su Recuerdo se Expande y su Ejemplo se Multiplica”</a>

		      	<h4><br> Nuestras redes</h4>
		      		
		      	<a href="https://www.instagram.com/elangeldelabicicletacastelli/?igshid=YmMyMTA2M2Y%3D">¡Instagram!</a>
		      	<h4> </h4>
		      	<a href="https://www.facebook.com/groups/498186250237283/?ref=share">¡Facebook!</a>
	      	</div>
			 
	  	</div>			
	</div>

{%endblock contenido%}

info/templates/home.html
{%extends 'base.html'%}
{%load static %}

{%block contenido%}
    <!-- Contenido -->

    <link rel="stylesheet" href="{% static 'css/home.css' %}">

        <div id="carouselExampleCaptions" class="carousel slide" data-bs-ride="false">
            <div class="carousel-indicators">
            <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
            <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="1" aria-label="Slide 2"></button>
            <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="2" aria-label="Slide 3"></button>
            </div>
            <div class="carousel-inner">
            <div class="carousel-item active">
                <img src="{% static 'img/home2.png' %}" class="d-block w-100" alt="...">
                <div class="carousel-caption d-none d-md-block">
                <h5>Comunidades Eclesiales de Base</h5>
                <p>Juan José Castelli</p>
                </div>
            </div>
            <div class="carousel-item">
                <img src="{% static 'img/home1.png' %}" class="d-block w-100" alt="...">
                <div class="carousel-caption d-none d-md-block">
                <h5>Opcion por los pobres</h5>
                <p>"Haciendo más visible la unión entre la fé y la vida"</p>
                </div>
            </div>
            <div class="carousel-item">
                <img src="{% static 'img/home3.png' %}" class="d-block w-100" alt="...">
                <div class="carousel-caption d-none d-md-block">
                <h5>Gracias por visitarnos!</h5>
                </div>
            </div>
            </div>
            <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Previous</span>
            </button>
            <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Next</span>
            </button>
        </div>

        <!--SIDE BAR - BODY-->
    <div class="container-l cont-noticia">  
        <div class="container-sm">
            <div class="row">
                <h3 class="text-center">Últimas Noticias</h3>
                {%for post in noticia %}
                <div class="col-sm-9 card card-noticia-home">
                    <div class="row p-2">
                        <div class="col-sm-4">
                            <img src="{{post.imagen.url}}" class="img-fluid rounded-start" alt="...">
                        </div>
                          <div class="col-sm-8">
                            <div class="card-body" style="position:relative;">
                              <h5 class="card-title">{{post}}</h5>
                              <p class="card-text">{{post.TextCorto}}</p>
                              <p class="card-text"><small class="text-muted">{{post.creado}}</small></p>
                              <a href="{%url 'noticias:MostrarNoticia' post.id %}"class="stretched-link"></a>
                            </div>
                          </div> 
                    </div>
          <!--          <div class="container-lg">
                        <div class="row">
                            <div class="col-sm-12" style="background-color:palegreen ;">
                                --SEPARADOR-- (Cards)
                            </div>
                        </div>
                    </div>-->
                </div>
            {%endfor%}
            </div>
            <a class="btn btn-primary" href="{%url 'noticias:listar_noticias' %}" role="button" style="margin-top: 0.5rem;">Ver más noticias...</a> 
        </div>
    </div>
  

    <div class="container-l cont-actividad">  
        <div class="container-sm">
            <div class="row">
                <h3 class="text-center">Últimas Actividades</h3>
                {% for post in actividad %}
                <div class="col-sm-9 card card-actividad-home">
                    <div class="row p-2">
                        <div class="col-sm-4">
                            <img src="{{post.imagen.url}}" class="img-fluid rounded-start" alt="...">
                        </div>
                          <div class="col-sm-8">
                            <div class="card-body" style="position:relative;">
                              <h5 class="card-title">{{post}}</h5>
                              <p class="card-text">{{post.cuerpo}}</p>
                              <p class="card-text"><small class="text-muted">{{post.fecha}}</small></p>
                              <a href="{% url 'actividades:detalle_actividad' post.pk %}"class="stretched-link"></a>
                            </div>
                          </div> 
                    </div>
                </div>
            {%endfor%}
            </div>
            <a class="btn btn-primary" href="{%url 'actividades:listar_actividades' %}" role="button" style="margin-top: 0.5rem;">Ver más actividades...</a>
        </div>
    </div>
{%endblock contenido%} 
        


  


  
    