info/apps/noticias/urls.py
from django.urls import path
from . import views

app_name='noticias'

urlpatterns = [
    path('listar/', views.Listar, name='listar_noticias'),
    path('listarPorFecha/', views.ListarporFecha, name='listar_noticiasporFecha'),
    path('MostrarNoticia/<int:pk>/', views.DetalleNoticia.as_view(), name='MostrarNoticia'),
    path('listarPatronales/', views.ListarPatronales, name='listar_noticiasPatronales'),
    path('listarSociales/', views.ListarSociales, name='listar_noticiasSociales'),
    path('add_comentario/<int:pk>', views.Agregar_Comentario, name="agregar_comentario"),
    path('delete_comentario/<int:pk>', views.Eliminar_Comentario, name="eliminar_comentario"),
]

info/info/urls.py
from django.contrib import admin
from django.urls import path,include

from django.conf.urls.static import static
from django.conf import settings

from . import views



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.Home, name = 'home'),
    path('contacto/', views.contacto, name = 'contacto'),
    path('mision_vision/', views.mision_vision, name = 'mision_vision'),
    path('eventos/', views.eventos, name = 'eventos'),
    path('noticias/',include('apps.noticias.urls')),
    path('usuarios/',include('apps.usuarios.urls')),
    path('Actividades/',include('apps.actividades.urls')),
    
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

info/apps/noticias/models.py
from distutils.command.upload import upload
from email.mime import image
import re
from django.db import models
from apps.usuarios.models import Usuario
# Create your models here.
class Categoria(models.Model):
    nombre = models.CharField(max_length=60)
    descripcion= models.CharField(max_length=250,null=True,blank=True)
    
    def __str__(self):
        return self.nombre
    
class Noticia(models.Model):
    titulo = models.CharField(max_length=120)
    creado = models.DateField(auto_now_add=True)
    cuerpo = models.TextField()
    autor= models.CharField(max_length=50, null=True, blank=True)
    imagen = models.ImageField(upload_to='noticias',null=True)
    categoria=models.ForeignKey(Categoria,on_delete=models.CASCADE,null=True)
    
    def __str__(self):
        return self.titulo
    
    def TextCorto(self):
        return self.cuerpo[:180]+"..."
    
    def obtener_mis_comentarios(self):
        return self.mis_comentarios.all()
       

class Comentario(models.Model):
	noticia = models.ForeignKey(Noticia, related_name = 'mis_comentarios', on_delete = models.CASCADE)
	texto = models.TextField()
	creado = models.DateTimeField(auto_now_add = True)
	usuario = models.ForeignKey(Usuario, related_name = 'usuario_comentario' , on_delete = models.CASCADE)

	def __str__(self):
		return self.texto
    

info/apps/noticias/views.py
from ast import Not
from datetime import date
from email import message
from gc import get_objects
from symtable import Class
from urllib import response
from django.shortcuts import render,get_object_or_404,redirect
from .models import Noticia
from django.core.paginator import Paginator
from django.views.generic import DetailView,DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin

from django.urls import reverse_lazy
from django.http import HttpResponseRedirect,HttpResponse


from .models import Noticia,Comentario

# Create your views here.

def Listar(request):
    #Creo el diccionario para pasar datos al templeate
    #ctx={}
    #Buscar las noticias de la BD
    todas=Noticia.objects.all()
    #Buscar lo que quiera de la BD
    #ctx['notis']=todas
    
    paginator=Paginator(todas,4)
    pagina= request.GET.get("page") or 1
    posts =paginator.get_page(pagina)
    currents_page= int(pagina)
    paginas=range(1,posts.paginator.num_pages+1)
    
    return render(request,'noticias/listar_noticias.html',{"posts":posts,"paginas":paginas,"currents_page":currents_page})
    #return render(request,'noticias/listar_noticias.html',ctx)

def ListarporFecha(request):
    todas=Noticia.objects.all().order_by('-creado')
    
    paginator=Paginator(todas,4)
    pagina= request.GET.get("page") or 1
    posts =paginator.get_page(pagina)
    currents_page= int(pagina)
    paginas=range(1,posts.paginator.num_pages+1)
    
    return render(request,'noticias/listar_noticias.html',{"posts":posts,"paginas":paginas,"currents_page":currents_page})


#def MostrarNoticia(request):
    #ctx={}
    #noticia=Noticia.objects.all()
    #ctx['noticia']=noticia
    #return render(request,'noticias/Pag_Noticia.html',ctx)
    
class DetalleNoticia(LoginRequiredMixin,DetailView):
    model=Noticia
    template_name='noticias/Detalle_Noticia.html'

def ListarPatronales(request):
    todas=Noticia.objects.all().filter(categoria=2)
    
    paginator=Paginator(todas,4)
    pagina= request.GET.get("page") or 1
    posts =paginator.get_page(pagina)
    currents_page= int(pagina)
    paginas=range(1,posts.paginator.num_pages+1)
    
    return render(request,'noticias/listar_noticias.html',{"posts":posts,"paginas":paginas,"currents_page":currents_page})

def ListarSociales(request):
    todas=Noticia.objects.all().filter(categoria=3)
    
    paginator=Paginator(todas,4)
    pagina= request.GET.get("page") or 1
    posts =paginator.get_page(pagina)
    currents_page= int(pagina)
    paginas=range(1,posts.paginator.num_pages+1)
    
    return render(request,'noticias/listar_noticias.html',{"posts":posts,"paginas":paginas,"currents_page":currents_page})


def Agregar_Comentario(request,pk):
	texto_comentario = request.POST.get('coment')
	
	#Forma 1 (es la mejor para este caso)
	noti = Noticia.objects.get(pk = pk)

	c = Comentario.objects.create(noticia = noti, texto = texto_comentario, usuario = request.user)

	return HttpResponseRedirect(reverse_lazy('noticias:MostrarNoticia' , kwargs={'pk':pk}))


def Eliminar_Comentario(request,pk):
    comentario=get_object_or_404(Comentario,id=pk)
    if comentario.usuario==request.user:
        comentario.delete()
        return HttpResponseRedirect(reverse_lazy('noticias:listar_noticias'))
    else:
        response=HttpResponse("NO TIENES PERMISO PARA ESTA ACCION")
        response.status_code=403
        return response
        

info/templates/noticias/Detalle_Noticia.html
{%extends 'base.html'%}
{%load static %}

{%block contenido%}

<div class="container">
    <div class="d-flex justify-content-center">
        <div class="card mb-3" style="width: 100%;">
            <div class="d-flex justify-content-center">
                <img src="{{object.imagen.url}}" class="card-img-top" alt="..." style="max-height:500px; ">
            </div>
            <div class="card-body">
            <h2 class="card-title">{{object}}</h2>
            <p class="card-text">{{object.cuerpo}}.</p>
            <p class="card-text"><small class="text-muted">Creado el: {{object.creado}}</small></p>
            <p class="card-text"><small class="text-muted">Autor: {{object.autor}} <br> Categoria:{{object.categoria}}</small></p>
            </div>
        </div>  
    </div>
    <h3>Deja un comentario</h3>
    <hr>

    <br>
    
   
    <ul class="nav nav-tabs" id="myTab" role="tablist">
        <li class="nav-item" role="presentation">
          <button class="nav-link active" id="home-tab" data-bs-toggle="tab" data-bs-target="#home-tab-pane" type="button" role="tab" aria-controls="home-tab-pane" aria-selected="true" style="background-color: rgb(61, 157, 170);">Comentarios</button>
        </li>
        <li class="nav-item" role="presentation">
          <button class="nav-link" id="profile-tab" data-bs-toggle="tab" data-bs-target="#profile-tab-pane" type="button" role="tab" aria-controls="profile-tab-pane" aria-selected="false" style="background-color: rgb(61, 157, 170); ">Comentar</button>
        </li>
    </ul>
    <div class="tab-content" id="myTabContent">
        <div class="tab-pane fade show active" id="home-tab-pane" role="tabpanel" aria-labelledby="home-tab" tabindex="0"> 
            {% for x in object.obtener_mis_comentarios %}
            <div class="card border-secondary mb-3" style="max-width: 50rem;">
                <div class="card-header" style="display: flex; justify-content:space-between;">
                        <label>Usuario: {{x.usuario}} </label> 
                        <a style="font-size:10
                        px ;" href="{% url 'noticias:eliminar_comentario' x.pk %}" class="btn-close" ></a>
                </div>
                <div class="card-body">
                    <p class="card-text">{{x.texto}}</p>
                    <p class="card-text"><small class="text-muted">{{x.creado}}</small></p>
                </div>
                    
            </div>
        {% endfor %}
        </div>
        <div class="tab-pane fade" id="profile-tab-pane" role="tabpanel" aria-labelledby="profile-tab" tabindex="0">    {% if user.is_authenticated %}
            <form method="POST" action="{% url 'noticias:agregar_comentario' object.pk %}" >{% csrf_token %}
                <div class="mb-1">
                    <label for="exampleFormControlInput1" class="form-label" style="font-size: 18px;">Usuario: {{user.username}}</label>
                  </div>
                  <div class="mb-3">
                    <textarea class="form-control" id="exampleFormControlTextarea1" rows="3" name="coment"></textarea>
                </div>
                <button type="submit" class="btn btn-outline-info">COMENTAR</button>
            </form>
        {% endif %}
        </div>
    </div>
      


    
</div>


{%endblock contenido%}

info/templates/noticias/listar_noticias.html
{%extends 'base.html'%}
{%load static %}

{%block contenido%}
<h2 class="p-2" style="text-align:center;margin-top:100px;">Noticias</h2>

<div class="container"style="max-width: 1100px;">
  <hr class="border border-primary border-2 opacity-50">
    <!---Filtrado-->
  <div class="d-flex justify-content-end pb-4">
    <div class="btn-group">
      <button type="button" class="btn btn-primary dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
      Filtrar
      </button>
      <ul class="dropdown-menu">
      <li><a class="dropdown-item" href="{%url 'noticias:listar_noticiasporFecha'%}">Más recientes</a></li>
      <li><a class="dropdown-item" href="{%url 'noticias:listar_noticias'%}">Más Antiguas</a></li>
      <li><a class="dropdown-item" href="{%url 'noticias:listar_noticiasPatronales'%}">Patronales</a></li>
      <li><a class="dropdown-item" href="{%url 'noticias:listar_noticiasSociales'%}">Sociales</a></li>
      </ul>
    </div>
  </div>
 
  <!----------------------->
    <div class="row row-cols-1 row-cols-md-2 g-4">
        {%for post in posts%}
        <div class="col">
          <div class="card shadow border" >
            <img src="{{post.imagen.url}} " class="card-img-top" alt="..." style="max-height: 500px;">
            <div class="card-body">
              <h6 class="list-group-item">{{post.creado}}</h6>
              <h5 class="card-title">{{ post }}</h5>
              <p class="card-text">{{ post.TextCorto }}.</p>
              
              <a type="button" class="btn btn-outline-primary" href="{%url 'noticias:MostrarNoticia' post.id %}">Saber más...</a>

            </div>
          </div>
        </div>
        {%endfor%}
    </div>
</div>
<!---Pagination-->
<br>
<br>
<nav aria-label="..." style="background-color:transparent;">
  <ul class="pagination justify-content-center">

    {%if posts.has_previous%}
    <li class="page-item">
      <a class="page-link" href="?page=1">Primera</a>
    </li>
    <li class="page-item">
      <a class="page-link" href="?page={{posts.previous_page_number}}">&laquo;</a>
    </li>
    {%endif%}

    {%for pagina in paginas%}
    <li class="page-item">
      <a class="page-link" href="?page={{pagina}}">{{pagina}}</a>
    </li>
    {%endfor%}
    
    {%if posts.has_next%}
    <li class="page-item">
      <a class="page-link" href="?page={{posts.next_page_number}}">&raquo;</a>
    </li>
    <li class="page-item"><a class="page-link" href="?page={{posts.paginator.num_pages}}">Ultima</a></li>
    {%endif%}
    
  </ul>
</nav>
{%endblock contenido%}